// Code generated by kubeagent/internal/gen. DO NOT EDIT.

package kubeagent

import (
	appsv1 "k8s.io/api/apps/v1"
	corev1 "k8s.io/api/core/v1"
	policyv1 "k8s.io/api/policy/v1"
	rbacv1 "k8s.io/api/rbac/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	intstr "k8s.io/apimachinery/pkg/util/intstr"
)

// Potential teleport.yaml payloads. Picked at runtime based on the specified roles.
const teleportConfigKube = `app_service:
  enabled: false
auth_service:
  enabled: false
db_service:
  enabled: false
discovery_service:
  enabled: false
jamf_service:
  enabled: false
kubernetes_service:
  enabled: true
  kube_cluster_name: cluster-placeholder
proxy_service:
  enabled: false
ssh_service:
  enabled: false
teleport:
  join_params:
    method: token
    token_name: /etc/teleport-secrets/auth-token
  log:
    format:
      extra_fields:
      - timestamp
      - level
      - component
      - caller
      output: text
    output: stderr
    severity: INFO
  proxy_server: proxy-placeholder:443
version: v3
`

const teleportConfigKubeAppDiscovery = `app_service:
  enabled: true
  resources:
  - labels:
      teleport.dev/kubernetes-cluster: cluster-placeholder
      teleport.dev/origin: discovery-kubernetes
auth_service:
  enabled: false
db_service:
  enabled: false
discovery_service:
  discovery_group: cluster-placeholder
  enabled: true
  kubernetes:
  - labels:
      '*': '*'
    namespaces:
    - '*'
    types:
    - app
jamf_service:
  enabled: false
kubernetes_service:
  enabled: true
  kube_cluster_name: cluster-placeholder
proxy_service:
  enabled: false
ssh_service:
  enabled: false
teleport:
  join_params:
    method: token
    token_name: /etc/teleport-secrets/auth-token
  log:
    format:
      extra_fields:
      - timestamp
      - level
      - component
      - caller
      output: text
    output: stderr
    severity: INFO
  proxy_server: proxy-placeholder:443
version: v3
`

// builtinImageTag is the chart's image tag at build time. The composer
// uses it as the version search target when an Options.AgentImage override
// is supplied, so embedded version strings (e.g. TELEPORT_EXT_UPGRADER_VERSION)
// match the new tag.
const builtinImageTag = "19.0.0-prealpha.2"

func genClusterRole(opts Options) *rbacv1.ClusterRole {
	return &rbacv1.ClusterRole{
		TypeMeta: metav1.TypeMeta{
			Kind:       "ClusterRole",
			APIVersion: "rbac.authorization.k8s.io/v1",
		},
		ObjectMeta: metav1.ObjectMeta{
			Name: "teleport-kube-agent",
		},
		Rules: []rbacv1.PolicyRule{
			rbacv1.PolicyRule{
				Verbs: []string{
					"impersonate",
				},
				APIGroups: []string{
					"",
				},
				Resources: []string{
					"users",
					"groups",
					"serviceaccounts",
				},
			},
			rbacv1.PolicyRule{
				Verbs: []string{
					"get",
				},
				APIGroups: []string{
					"",
				},
				Resources: []string{
					"pods",
				},
			},
			rbacv1.PolicyRule{
				Verbs: []string{
					"create",
				},
				APIGroups: []string{
					"authorization.k8s.io",
				},
				Resources: []string{
					"selfsubjectaccessreviews",
				},
			},
		},
	}
}

func genClusterRoleBinding(opts Options) *rbacv1.ClusterRoleBinding {
	return &rbacv1.ClusterRoleBinding{
		TypeMeta: metav1.TypeMeta{
			Kind:       "ClusterRoleBinding",
			APIVersion: "rbac.authorization.k8s.io/v1",
		},
		ObjectMeta: metav1.ObjectMeta{
			Name: "teleport-kube-agent",
		},
		Subjects: []rbacv1.Subject{
			rbacv1.Subject{
				Kind:      "ServiceAccount",
				Name:      "teleport-kube-agent",
				Namespace: "ns-placeholder",
			},
		},
		RoleRef: rbacv1.RoleRef{
			APIGroup: "rbac.authorization.k8s.io",
			Kind:     "ClusterRole",
			Name:     "teleport-kube-agent",
		},
	}
}

func genConfigMap(opts Options) *corev1.ConfigMap {
	return &corev1.ConfigMap{
		TypeMeta: metav1.TypeMeta{
			Kind:       "ConfigMap",
			APIVersion: "v1",
		},
		ObjectMeta: metav1.ObjectMeta{
			Name:      "teleport-kube-agent",
			Namespace: "ns-placeholder",
		},
	}
}

func genUpdaterDeployment(opts Options) *appsv1.Deployment {
	return &appsv1.Deployment{
		TypeMeta: metav1.TypeMeta{
			Kind:       "Deployment",
			APIVersion: "apps/v1",
		},
		ObjectMeta: metav1.ObjectMeta{
			Name:      "teleport-kube-agent-updater",
			Namespace: "ns-placeholder",
			Labels: map[string]string{
				"app": "teleport-kube-agent-updater",
			},
		},
		Spec: appsv1.DeploymentSpec{
			Replicas: ptr(int32(1)),
			Selector: ptr(metav1.LabelSelector{
				MatchLabels: map[string]string{
					"app": "teleport-kube-agent-updater",
				},
			}),
			Template: corev1.PodTemplateSpec{
				ObjectMeta: metav1.ObjectMeta{
					Labels: map[string]string{
						"app": "teleport-kube-agent-updater",
					},
				},
				Spec: corev1.PodSpec{
					Containers: []corev1.Container{
						corev1.Container{
							Name:  "kube-agent-updater",
							Image: "public.ecr.aws/gravitational/teleport-kube-agent-updater:19.0.0-prealpha.2",
							Args: []string{
								"--agent-name=teleport-kube-agent",
								"--agent-namespace=ns-placeholder",
								"--base-image=public.ecr.aws/gravitational/teleport-ent-distroless",
								"--version-server=https://proxy-placeholder:443/v1/webapi/automaticupgrades/channel",
								"--version-channel=channel-placeholder",
								"--proxy-address=proxy-placeholder:443",
								"--update-group=default",
							},
							Ports: []corev1.ContainerPort{
								corev1.ContainerPort{
									Name:          "metrics",
									ContainerPort: 8080,
									Protocol:      corev1.Protocol("TCP"),
								},
								corev1.ContainerPort{
									Name:          "healthz",
									ContainerPort: 8081,
									Protocol:      corev1.Protocol("TCP"),
								},
							},
							LivenessProbe: ptr(corev1.Probe{
								ProbeHandler: corev1.ProbeHandler{
									HTTPGet: ptr(corev1.HTTPGetAction{
										Path: "/healthz",
										Port: intstr.FromString("healthz"),
									}),
								},
								InitialDelaySeconds: 5,
								TimeoutSeconds:      5,
								PeriodSeconds:       5,
								FailureThreshold:    6,
							}),
							ReadinessProbe: ptr(corev1.Probe{
								ProbeHandler: corev1.ProbeHandler{
									HTTPGet: ptr(corev1.HTTPGetAction{
										Path: "/readyz",
										Port: intstr.FromString("healthz"),
									}),
								},
								InitialDelaySeconds: 5,
								TimeoutSeconds:      5,
								PeriodSeconds:       5,
								FailureThreshold:    6,
							}),
							ImagePullPolicy: corev1.PullPolicy("IfNotPresent"),
							SecurityContext: ptr(corev1.SecurityContext{
								Capabilities: ptr(corev1.Capabilities{
									Drop: []corev1.Capability{
										corev1.Capability("ALL"),
									},
								}),
								RunAsUser:                ptr(int64(9807)),
								RunAsNonRoot:             ptr(true),
								ReadOnlyRootFilesystem:   ptr(true),
								AllowPrivilegeEscalation: ptr(false),
								SeccompProfile: ptr(corev1.SeccompProfile{
									Type: corev1.SeccompProfileType("RuntimeDefault"),
								}),
							}),
						},
					},
					ServiceAccountName: "teleport-kube-agent-updater",
				},
			},
		},
	}
}

func genPodDisruptionBudget(opts Options) *policyv1.PodDisruptionBudget {
	return &policyv1.PodDisruptionBudget{
		TypeMeta: metav1.TypeMeta{
			Kind:       "PodDisruptionBudget",
			APIVersion: "policy/v1",
		},
		ObjectMeta: metav1.ObjectMeta{
			Name:      "teleport-kube-agent",
			Namespace: "ns-placeholder",
			Labels: map[string]string{
				"app": "teleport-kube-agent",
			},
		},
		Spec: policyv1.PodDisruptionBudgetSpec{
			MinAvailable: ptr(intstr.FromInt32(1)),
			Selector: ptr(metav1.LabelSelector{
				MatchLabels: map[string]string{
					"app": "teleport-kube-agent",
				},
			}),
		},
	}
}

func genRole(opts Options) *rbacv1.Role {
	return &rbacv1.Role{
		TypeMeta: metav1.TypeMeta{
			Kind:       "Role",
			APIVersion: "rbac.authorization.k8s.io/v1",
		},
		ObjectMeta: metav1.ObjectMeta{
			Name:      "teleport-kube-agent",
			Namespace: "ns-placeholder",
		},
		Rules: []rbacv1.PolicyRule{
			rbacv1.PolicyRule{
				Verbs: []string{
					"create",
					"get",
					"update",
					"patch",
				},
				APIGroups: []string{
					"",
				},
				Resources: []string{
					"secrets",
				},
			},
		},
	}
}

func genUpdaterRole(opts Options) *rbacv1.Role {
	return &rbacv1.Role{
		TypeMeta: metav1.TypeMeta{
			Kind:       "Role",
			APIVersion: "rbac.authorization.k8s.io/v1",
		},
		ObjectMeta: metav1.ObjectMeta{
			Name:      "teleport-kube-agent-updater",
			Namespace: "ns-placeholder",
		},
		Rules: []rbacv1.PolicyRule{
			rbacv1.PolicyRule{
				Verbs: []string{
					"get",
					"watch",
					"list",
					"delete",
				},
				APIGroups: []string{
					"",
				},
				Resources: []string{
					"pods",
				},
			},
			rbacv1.PolicyRule{
				Verbs: []string{
					"get",
					"watch",
					"list",
				},
				APIGroups: []string{
					"",
				},
				Resources: []string{
					"pods/status",
				},
			},
			rbacv1.PolicyRule{
				Verbs: []string{
					"watch",
					"list",
				},
				APIGroups: []string{
					"",
				},
				Resources: []string{
					"secrets",
				},
			},
			rbacv1.PolicyRule{
				Verbs: []string{
					"get",
				},
				APIGroups: []string{
					"",
				},
				Resources: []string{
					"secrets",
				},
				ResourceNames: []string{
					"teleport-kube-agent-shared-state",
				},
			},
			rbacv1.PolicyRule{
				Verbs: []string{
					"create",
					"patch",
				},
				APIGroups: []string{
					"",
				},
				Resources: []string{
					"events",
				},
			},
			rbacv1.PolicyRule{
				Verbs: []string{
					"create",
					"watch",
					"list",
				},
				APIGroups: []string{
					"",
				},
				Resources: []string{
					"configmaps",
				},
			},
			rbacv1.PolicyRule{
				Verbs: []string{
					"get",
					"update",
				},
				APIGroups: []string{
					"",
				},
				Resources: []string{
					"configmaps",
				},
				ResourceNames: []string{
					"teleport-kube-agent-updater",
				},
			},
			rbacv1.PolicyRule{
				Verbs: []string{
					"get",
					"watch",
					"list",
				},
				APIGroups: []string{
					"apps",
				},
				Resources: []string{
					"deployments",
					"statefulsets",
					"deployments/status",
					"statefulsets/status",
				},
			},
			rbacv1.PolicyRule{
				Verbs: []string{
					"update",
				},
				APIGroups: []string{
					"apps",
				},
				Resources: []string{
					"deployments",
					"statefulsets",
				},
				ResourceNames: []string{
					"teleport-kube-agent",
				},
			},
			rbacv1.PolicyRule{
				Verbs: []string{
					"create",
				},
				APIGroups: []string{
					"coordination.k8s.io",
				},
				Resources: []string{
					"leases",
				},
			},
			rbacv1.PolicyRule{
				Verbs: []string{
					"get",
					"update",
				},
				APIGroups: []string{
					"coordination.k8s.io",
				},
				Resources: []string{
					"leases",
				},
				ResourceNames: []string{
					"teleport-kube-agent",
				},
			},
		},
	}
}

func genRoleBinding(opts Options) *rbacv1.RoleBinding {
	return &rbacv1.RoleBinding{
		TypeMeta: metav1.TypeMeta{
			Kind:       "RoleBinding",
			APIVersion: "rbac.authorization.k8s.io/v1",
		},
		ObjectMeta: metav1.ObjectMeta{
			Name:      "teleport-kube-agent",
			Namespace: "ns-placeholder",
		},
		Subjects: []rbacv1.Subject{
			rbacv1.Subject{
				Kind:      "ServiceAccount",
				Name:      "teleport-kube-agent",
				Namespace: "ns-placeholder",
			},
		},
		RoleRef: rbacv1.RoleRef{
			APIGroup: "rbac.authorization.k8s.io",
			Kind:     "Role",
			Name:     "teleport-kube-agent",
		},
	}
}

func genUpdaterRoleBinding(opts Options) *rbacv1.RoleBinding {
	return &rbacv1.RoleBinding{
		TypeMeta: metav1.TypeMeta{
			Kind:       "RoleBinding",
			APIVersion: "rbac.authorization.k8s.io/v1",
		},
		ObjectMeta: metav1.ObjectMeta{
			Name:      "teleport-kube-agent-updater",
			Namespace: "ns-placeholder",
		},
		Subjects: []rbacv1.Subject{
			rbacv1.Subject{
				Kind:      "ServiceAccount",
				Name:      "teleport-kube-agent-updater",
				Namespace: "ns-placeholder",
			},
		},
		RoleRef: rbacv1.RoleRef{
			APIGroup: "rbac.authorization.k8s.io",
			Kind:     "Role",
			Name:     "teleport-kube-agent-updater",
		},
	}
}

func genSecret(opts Options) *corev1.Secret {
	return &corev1.Secret{
		TypeMeta: metav1.TypeMeta{
			Kind:       "Secret",
			APIVersion: "v1",
		},
		ObjectMeta: metav1.ObjectMeta{
			Name:      "teleport-kube-agent-join-token",
			Namespace: "ns-placeholder",
		},
		StringData: map[string]string{
			"auth-token": "token-placeholder\n",
		},
		Type: corev1.SecretType("Opaque"),
	}
}

func genServiceAccount(opts Options) *corev1.ServiceAccount {
	return &corev1.ServiceAccount{
		TypeMeta: metav1.TypeMeta{
			Kind:       "ServiceAccount",
			APIVersion: "v1",
		},
		ObjectMeta: metav1.ObjectMeta{
			Name:      "teleport-kube-agent",
			Namespace: "ns-placeholder",
		},
		AutomountServiceAccountToken: ptr(false),
	}
}

func genUpdaterServiceAccount(opts Options) *corev1.ServiceAccount {
	return &corev1.ServiceAccount{
		TypeMeta: metav1.TypeMeta{
			Kind:       "ServiceAccount",
			APIVersion: "v1",
		},
		ObjectMeta: metav1.ObjectMeta{
			Name:      "teleport-kube-agent-updater",
			Namespace: "ns-placeholder",
		},
	}
}

func genStatefulSet(opts Options) *appsv1.StatefulSet {
	return &appsv1.StatefulSet{
		TypeMeta: metav1.TypeMeta{
			Kind:       "StatefulSet",
			APIVersion: "apps/v1",
		},
		ObjectMeta: metav1.ObjectMeta{
			Name:      "teleport-kube-agent",
			Namespace: "ns-placeholder",
			Labels: map[string]string{
				"app": "teleport-kube-agent",
			},
		},
		Spec: appsv1.StatefulSetSpec{
			Replicas: ptr(int32(2)),
			Selector: ptr(metav1.LabelSelector{
				MatchLabels: map[string]string{
					"app": "teleport-kube-agent",
				},
			}),
			Template: corev1.PodTemplateSpec{
				ObjectMeta: metav1.ObjectMeta{
					Labels: map[string]string{
						"app": "teleport-kube-agent",
					},
					Annotations: map[string]string{
						"checksum/config": "1b5a7f12dea340098047bfdacb3ea2087bb0cae0bb42560d575ff1f9f07a0f1b",
					},
				},
				Spec: corev1.PodSpec{
					Volumes: []corev1.Volume{
						corev1.Volume{
							Name: "config",
							VolumeSource: corev1.VolumeSource{
								ConfigMap: ptr(corev1.ConfigMapVolumeSource{
									LocalObjectReference: corev1.LocalObjectReference{
										Name: "teleport-kube-agent",
									},
								}),
							},
						},
						corev1.Volume{
							Name: "auth-token",
							VolumeSource: corev1.VolumeSource{
								Secret: ptr(corev1.SecretVolumeSource{
									SecretName: "teleport-kube-agent-join-token",
								}),
							},
						},
						corev1.Volume{
							Name: "data",
							VolumeSource: corev1.VolumeSource{
								EmptyDir: ptr(corev1.EmptyDirVolumeSource{}),
							},
						},
						corev1.Volume{
							Name: "updater-config",
							VolumeSource: corev1.VolumeSource{
								ConfigMap: ptr(corev1.ConfigMapVolumeSource{
									LocalObjectReference: corev1.LocalObjectReference{
										Name: "teleport-kube-agent-updater",
									},
								}),
							},
						},
					},
					Containers: []corev1.Container{
						corev1.Container{
							Name:  "teleport",
							Image: "public.ecr.aws/gravitational/teleport-ent-distroless:19.0.0-prealpha.2",
							Args: []string{
								"--diag-addr=0.0.0.0:3000",
							},
							Ports: []corev1.ContainerPort{
								corev1.ContainerPort{
									Name:          "diag",
									ContainerPort: 3000,
									Protocol:      corev1.Protocol("TCP"),
								},
							},
							Env: []corev1.EnvVar{
								corev1.EnvVar{
									Name:  "TELEPORT_INSTALL_METHOD_HELM_KUBE_AGENT",
									Value: "true",
								},
								corev1.EnvVar{
									Name: "TELEPORT_REPLICA_NAME",
									ValueFrom: ptr(corev1.EnvVarSource{
										FieldRef: ptr(corev1.ObjectFieldSelector{
											FieldPath: "metadata.name",
										}),
									}),
								},
								corev1.EnvVar{
									Name: "KUBE_NAMESPACE",
									ValueFrom: ptr(corev1.EnvVarSource{
										FieldRef: ptr(corev1.ObjectFieldSelector{
											FieldPath: "metadata.namespace",
										}),
									}),
								},
								corev1.EnvVar{
									Name:  "RELEASE_NAME",
									Value: "teleport-kube-agent",
								},
								corev1.EnvVar{
									Name:  "TELEPORT_EXT_UPGRADER",
									Value: "kube",
								},
								corev1.EnvVar{
									Name:  "TELEPORT_EXT_UPGRADER_VERSION",
									Value: "19.0.0-prealpha.2",
								},
								corev1.EnvVar{
									Name:  "TELEPORT_KUBE_CLUSTER_DOMAIN",
									Value: "cluster.local",
								},
								corev1.EnvVar{
									Name:  "TELEPORT_UPDATE_CONFIG_FILE",
									Value: "/etc/updater-config/update.yaml",
								},
							},
							VolumeMounts: []corev1.VolumeMount{
								corev1.VolumeMount{
									Name:      "config",
									ReadOnly:  true,
									MountPath: "/etc/teleport",
								},
								corev1.VolumeMount{
									Name:      "auth-token",
									ReadOnly:  true,
									MountPath: "/etc/teleport-secrets",
								},
								corev1.VolumeMount{
									Name:      "data",
									MountPath: "/var/lib/teleport",
								},
								corev1.VolumeMount{
									Name:      "updater-config",
									ReadOnly:  true,
									MountPath: "/etc/updater-config",
								},
							},
							LivenessProbe: ptr(corev1.Probe{
								ProbeHandler: corev1.ProbeHandler{
									HTTPGet: ptr(corev1.HTTPGetAction{
										Path: "/healthz",
										Port: intstr.FromString("diag"),
									}),
								},
								InitialDelaySeconds: 5,
								TimeoutSeconds:      1,
								PeriodSeconds:       5,
								FailureThreshold:    6,
							}),
							ReadinessProbe: ptr(corev1.Probe{
								ProbeHandler: corev1.ProbeHandler{
									HTTPGet: ptr(corev1.HTTPGetAction{
										Path: "/readyz",
										Port: intstr.FromString("diag"),
									}),
								},
								InitialDelaySeconds: 5,
								TimeoutSeconds:      1,
								PeriodSeconds:       5,
								FailureThreshold:    12,
							}),
							ImagePullPolicy: corev1.PullPolicy("IfNotPresent"),
							SecurityContext: ptr(corev1.SecurityContext{
								Capabilities: ptr(corev1.Capabilities{
									Drop: []corev1.Capability{
										corev1.Capability("ALL"),
									},
								}),
								RunAsUser:                ptr(int64(9807)),
								RunAsNonRoot:             ptr(true),
								ReadOnlyRootFilesystem:   ptr(true),
								AllowPrivilegeEscalation: ptr(false),
								SeccompProfile: ptr(corev1.SeccompProfile{
									Type: corev1.SeccompProfileType("RuntimeDefault"),
								}),
							}),
						},
					},
					TerminationGracePeriodSeconds: ptr(int64(30)),
					ServiceAccountName:            "teleport-kube-agent",
					AutomountServiceAccountToken:  ptr(true),
					SecurityContext: ptr(corev1.PodSecurityContext{
						FSGroup: ptr(int64(9807)),
					}),
					Affinity: ptr(corev1.Affinity{
						PodAntiAffinity: ptr(corev1.PodAntiAffinity{
							PreferredDuringSchedulingIgnoredDuringExecution: []corev1.WeightedPodAffinityTerm{
								corev1.WeightedPodAffinityTerm{
									Weight: 50,
									PodAffinityTerm: corev1.PodAffinityTerm{
										LabelSelector: ptr(metav1.LabelSelector{
											MatchExpressions: []metav1.LabelSelectorRequirement{
												metav1.LabelSelectorRequirement{
													Key:      "app",
													Operator: metav1.LabelSelectorOperator("In"),
													Values: []string{
														"teleport-kube-agent",
													},
												},
											},
										}),
										TopologyKey: "kubernetes.io/hostname",
									},
								},
							},
						}),
					}),
					TopologySpreadConstraints: []corev1.TopologySpreadConstraint{
						corev1.TopologySpreadConstraint{
							MaxSkew:           1,
							TopologyKey:       "kubernetes.io/hostname",
							WhenUnsatisfiable: corev1.UnsatisfiableConstraintAction("ScheduleAnyway"),
							LabelSelector: ptr(metav1.LabelSelector{
								MatchLabels: map[string]string{
									"app": "teleport-kube-agent",
								},
							}),
						},
						corev1.TopologySpreadConstraint{
							MaxSkew:           1,
							TopologyKey:       "topology.kubernetes.io/zone",
							WhenUnsatisfiable: corev1.UnsatisfiableConstraintAction("ScheduleAnyway"),
							LabelSelector: ptr(metav1.LabelSelector{
								MatchLabels: map[string]string{
									"app": "teleport-kube-agent",
								},
							}),
						},
					},
				},
			},
			ServiceName: "teleport-kube-agent",
		},
	}
}
